services:
    backend:
        build:
            context: .
            dockerfile: dockerfile.dev
        container_name: backend-metering
        environment:
            - NODE_ENV=development
            - MONGO_URL=mongodb://root:pass12345@mongodb:27017
        volumes:
            - .:/app
