services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      - ./mongo_db:/data/db
    ports:
      - '27017:27017'
    restart: on-failure:3
    command: [ --auth ]

  backend:
    build:
        context: .
        dockerfile: dockerfile.dev
    container_name: backend-metering
    environment:
        - NODE_ENV=development
        - MONGO_URL=mongodb://root:pass12345@mongodb:27017
    volumes:
        - .:/app
    depends_on:
      - mongodb
    restart: on-failure:3
    ports:
        - '3001:3001'

  wrx_server:
    build:
      context: ../metering_tcp_wrx_server
      dockerfile: dockerfile.dev
    container_name: wrx_server
    environment:
      - NODE_ENV=development
    volumes:
      - ../metering_tcp_wrx_server:/app
    restart: on-failure:3
    ports:
      - '4000:4000'
      - '4001:4001'
    command: ["npm", "run", "dev"]
