services:
    mongodb:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=pass12345
        volumes:
            - ./mongo_db:/data/db
        ports:
            - '27017:27017'
        restart: on-failure:3
        command: [--auth]

    backend:
        depends_on:
            - mongodb
        restart: on-failure:3
        ports:
            - '3001:3001'


